package koGenerator;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import org.springframework.format.annotation.DateTimeFormat;


@Entity
@Table(name="DETALHE_TIPO_FREQUENCIA")
@Getter @Setter @AllArgsConstructor @NoArgsConstructor
public class DetalheTipoFrequencia implements Serializable {
	/**
	 * Generated by IDE
	 */
	private static final long serialVersionUID = 3581205333645805460L;

	@Id
    @SequenceGenerator(name = "SEQ_DETALHE_TIPO_FREQUENCIA", sequenceName = "SEQ_DETALHE_TIPO_FREQUENCIA", allocationSize = 0)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_DETALHE_TIPO_FREQUENCIA")
    @Column(name = "CD_DETALHE_TIPO_FREQUENCIA", length = 6, nullable = false)
    private Long id;
    
    @ManyToOne
    @JoinColumn(name = "CD_TIPO_FREQUENCIA", referencedColumnName = "CD_TIPO_FREQUENCIA", nullable = false)
    private TipoFrequencia tipoFrequencia;
    
    @Column(name = "DS_MEDICACAO")
    @Size(max = 150)
    private String descricaoMedicamento;
    
    @Column (name = "HR_MEDICACAO")
    @NotNull
    @Temporal(TemporalType.TIME)
    @DateTimeFormat(pattern = "hh:mm")
    private Date horaMedicacao;


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DetalheTipoFrequencia other = (DetalheTipoFrequencia) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}    
}